version: "3.9"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - node-network
  app:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app/rentx
    networks:
      - node-network
    depends_on:
      - database_ignite

networks:
  node-network:
    driver: bridge

volumes:
  pgdata:
    driver: local